weights: /home/tanyadiplom/Static_YOLOMG/runs/train/ard100_videoOnly_adaptiveFusion_b56_e30_pat7_from_videoNative_physgpu0/weights/last.pt
cfg: ''
data: data/ard100_video.yaml
hyp: data/hyps/hyp.mixed_finetune_640_minimal.yaml
epochs: 30
batch_size: 56
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 4
project: runs/train
name: ard100_videoOnly_adaptiveFusion_b56_e30_pat7_from_videoNative_physgpu0
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 7
freeze:
- 0
save_period: -1
save_interval_batches: 500
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
save_dir: runs/train/ard100_videoOnly_adaptiveFusion_b56_e30_pat7_from_videoNative_physgpu0
