weights: /home/tanyadiplom/Static_YOLOMG/runs/train/ard100_mixed640_zeroP_vidDrop03_from_vidbest_gpu0/weights/best.pt
cfg: models/NPS_uav_s.yaml
data: data/ard100_mixed.yaml
hyp: data/hyps/hyp.mixed_finetune_640_minimal.yaml
epochs: 10
batch_size: 56
imgsz: 640
rect: false
resume: ''
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 4
project: runs/train
name: ard100_mixed640_clahe_dog_vidNativeFD_e10p5_from_mixed640best_gpu1
exist_ok: true
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 5
freeze:
- 0
save_period: -1
save_interval_batches: 500
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
save_dir: runs/train/ard100_mixed640_clahe_dog_vidNativeFD_e10p5_from_mixed640best_gpu1
